### PR TITLE
[REG-1495] Update reference to 'gg.regression.unity.bots'

### PR DESCRIPTION
**Pull request by analogrelay**
Updates reference to RGUnityBots to react to https://github.com/Regression-Games/RGUnityBots/pull/121

This does not check or correct any other issues that may exist in the sample. I did ensure the Unity project loads and resolves the package correctly, and load the project which may have caused generated code to be re-generated.

--

TODO:
* [x] Reopen after merging https://github.com/Regression-Games/RGUnityBots/pull/121 to ensure `package-lock.json` gets updated with the right hash.

### CODE REVIEW

**Comment by analogrelay** [comment]
This one is draft because it uses a Git reference. I've updated it to be correct when the PR to RGUnityBots lands, but if you open it now it will fail because it's pointing at `main` which hasn't been reorganized.

**Comment by analogrelay** [comment]
Updated git reference. Again, this sample has no local bot that I can find so I'm not sure it's worth the work to build one.

**Comment by analogrelay** [comment]
Build failure appears to be an issue with the Unity license and not directly related to these changes.

image

**Review by nAmKcAz — APPROVED** [review]

**Review by vontell — APPROVED** [review]
Yeah this was made before local bots existed. Approving!

**Pull request merged**
